### ISSUE TITLE
Definir o escopo dos testes de unidade

### ISSUE THREAD

**Issue by regiosousa** [CleideGomes/caixeiro_viajente#2]
Checar o código do projeto e identificar as unidades testáveis.

Enumerar as unidades e criar os testes para cada uma delas.

**Comment by CleideGomes** [comment]
## Teste de Cidades:

1 - getDistancia - dado a distancia entre uma origem e um destino deve retornar uma distância;

2 - getDistanciaTotal - dado um percurso deve retornar uma distância total;

3 - getPercursoAleatorio -  retorna um percurso aleatório;

## Teste de Cromossomo:

1 - toString - retornar um texto com a string da primeira cidade e a distancia total;

2 - getAptidao - retorna a distancia total

3 - getGenes - retorna o caminho escolhido;

4 - compareTo - recebe uma instância de cromossomo e compara se a distancia é maior ou menor ou igual deve retornar 1 para maior -1 para menor e 0 se for igual;

## Teste de População:

1 - toString - retorna uma string;

2 - getMelhorCromossomo - retorna o melhor caminho;
